// Code generated by ent, DO NOT EDIT.

package scenariocandidate

import (
	"ekko/pkg/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldUpdatedAt, v))
}

// CandidateID applies equality check predicate on the "candidate_id" field. It's identical to CandidateIDEQ.
func CandidateID(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldCandidateID, v))
}

// ScenarioID applies equality check predicate on the "scenario_id" field. It's identical to ScenarioIDEQ.
func ScenarioID(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldScenarioID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldLTE(FieldUpdatedAt, v))
}

// CandidateIDEQ applies the EQ predicate on the "candidate_id" field.
func CandidateIDEQ(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldCandidateID, v))
}

// CandidateIDNEQ applies the NEQ predicate on the "candidate_id" field.
func CandidateIDNEQ(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNEQ(FieldCandidateID, v))
}

// CandidateIDIn applies the In predicate on the "candidate_id" field.
func CandidateIDIn(vs ...uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldIn(FieldCandidateID, vs...))
}

// CandidateIDNotIn applies the NotIn predicate on the "candidate_id" field.
func CandidateIDNotIn(vs ...uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNotIn(FieldCandidateID, vs...))
}

// CandidateIDGT applies the GT predicate on the "candidate_id" field.
func CandidateIDGT(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldGT(FieldCandidateID, v))
}

// CandidateIDGTE applies the GTE predicate on the "candidate_id" field.
func CandidateIDGTE(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldGTE(FieldCandidateID, v))
}

// CandidateIDLT applies the LT predicate on the "candidate_id" field.
func CandidateIDLT(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldLT(FieldCandidateID, v))
}

// CandidateIDLTE applies the LTE predicate on the "candidate_id" field.
func CandidateIDLTE(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldLTE(FieldCandidateID, v))
}

// ScenarioIDEQ applies the EQ predicate on the "scenario_id" field.
func ScenarioIDEQ(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldEQ(FieldScenarioID, v))
}

// ScenarioIDNEQ applies the NEQ predicate on the "scenario_id" field.
func ScenarioIDNEQ(v uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNEQ(FieldScenarioID, v))
}

// ScenarioIDIn applies the In predicate on the "scenario_id" field.
func ScenarioIDIn(vs ...uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldIn(FieldScenarioID, vs...))
}

// ScenarioIDNotIn applies the NotIn predicate on the "scenario_id" field.
func ScenarioIDNotIn(vs ...uint64) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.FieldNotIn(FieldScenarioID, vs...))
}

// HasScenario applies the HasEdge predicate on the "scenario" edge.
func HasScenario() predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScenarioTable, ScenarioColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScenarioWith applies the HasEdge predicate on the "scenario" edge with a given conditions (other predicates).
func HasScenarioWith(preds ...predicate.Scenario) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(func(s *sql.Selector) {
		step := newScenarioStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttempts applies the HasEdge predicate on the "attempts" edge.
func HasAttempts() predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttemptsTable, AttemptsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttemptsWith applies the HasEdge predicate on the "attempts" edge with a given conditions (other predicates).
func HasAttemptsWith(preds ...predicate.SubmissionAttempt) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(func(s *sql.Selector) {
		step := newAttemptsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScenarioCandidate) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScenarioCandidate) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScenarioCandidate) predicate.ScenarioCandidate {
	return predicate.ScenarioCandidate(sql.NotPredicates(p))
}
