// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ekko/pkg/ent/question"
	"ekko/pkg/ent/scenario"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionCreate is the builder for creating a Question entity.
type QuestionCreate struct {
	config
	mutation *QuestionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (qc *QuestionCreate) SetCreatedAt(t time.Time) *QuestionCreate {
	qc.mutation.SetCreatedAt(t)
	return qc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (qc *QuestionCreate) SetNillableCreatedAt(t *time.Time) *QuestionCreate {
	if t != nil {
		qc.SetCreatedAt(*t)
	}
	return qc
}

// SetUpdatedAt sets the "updated_at" field.
func (qc *QuestionCreate) SetUpdatedAt(t time.Time) *QuestionCreate {
	qc.mutation.SetUpdatedAt(t)
	return qc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (qc *QuestionCreate) SetNillableUpdatedAt(t *time.Time) *QuestionCreate {
	if t != nil {
		qc.SetUpdatedAt(*t)
	}
	return qc
}

// SetScenarioID sets the "scenario_id" field.
func (qc *QuestionCreate) SetScenarioID(u uint64) *QuestionCreate {
	qc.mutation.SetScenarioID(u)
	return qc
}

// SetCriteria sets the "criteria" field.
func (qc *QuestionCreate) SetCriteria(s string) *QuestionCreate {
	qc.mutation.SetCriteria(s)
	return qc
}

// SetHint sets the "hint" field.
func (qc *QuestionCreate) SetHint(s string) *QuestionCreate {
	qc.mutation.SetHint(s)
	return qc
}

// SetContent sets the "content" field.
func (qc *QuestionCreate) SetContent(s string) *QuestionCreate {
	qc.mutation.SetContent(s)
	return qc
}

// SetID sets the "id" field.
func (qc *QuestionCreate) SetID(u uint64) *QuestionCreate {
	qc.mutation.SetID(u)
	return qc
}

// SetScenario sets the "scenario" edge to the Scenario entity.
func (qc *QuestionCreate) SetScenario(s *Scenario) *QuestionCreate {
	return qc.SetScenarioID(s.ID)
}

// Mutation returns the QuestionMutation object of the builder.
func (qc *QuestionCreate) Mutation() *QuestionMutation {
	return qc.mutation
}

// Save creates the Question in the database.
func (qc *QuestionCreate) Save(ctx context.Context) (*Question, error) {
	qc.defaults()
	return withHooks(ctx, qc.sqlSave, qc.mutation, qc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qc *QuestionCreate) SaveX(ctx context.Context) *Question {
	v, err := qc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qc *QuestionCreate) Exec(ctx context.Context) error {
	_, err := qc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qc *QuestionCreate) ExecX(ctx context.Context) {
	if err := qc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qc *QuestionCreate) defaults() {
	if _, ok := qc.mutation.CreatedAt(); !ok {
		v := question.DefaultCreatedAt()
		qc.mutation.SetCreatedAt(v)
	}
	if _, ok := qc.mutation.UpdatedAt(); !ok {
		v := question.DefaultUpdatedAt()
		qc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qc *QuestionCreate) check() error {
	if _, ok := qc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Question.created_at"`)}
	}
	if _, ok := qc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Question.updated_at"`)}
	}
	if _, ok := qc.mutation.ScenarioID(); !ok {
		return &ValidationError{Name: "scenario_id", err: errors.New(`ent: missing required field "Question.scenario_id"`)}
	}
	if _, ok := qc.mutation.Criteria(); !ok {
		return &ValidationError{Name: "criteria", err: errors.New(`ent: missing required field "Question.criteria"`)}
	}
	if _, ok := qc.mutation.Hint(); !ok {
		return &ValidationError{Name: "hint", err: errors.New(`ent: missing required field "Question.hint"`)}
	}
	if _, ok := qc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Question.content"`)}
	}
	if len(qc.mutation.ScenarioIDs()) == 0 {
		return &ValidationError{Name: "scenario", err: errors.New(`ent: missing required edge "Question.scenario"`)}
	}
	return nil
}

func (qc *QuestionCreate) sqlSave(ctx context.Context) (*Question, error) {
	if err := qc.check(); err != nil {
		return nil, err
	}
	_node, _spec := qc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	qc.mutation.id = &_node.ID
	qc.mutation.done = true
	return _node, nil
}

func (qc *QuestionCreate) createSpec() (*Question, *sqlgraph.CreateSpec) {
	var (
		_node = &Question{config: qc.config}
		_spec = sqlgraph.NewCreateSpec(question.Table, sqlgraph.NewFieldSpec(question.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = qc.conflict
	if id, ok := qc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := qc.mutation.CreatedAt(); ok {
		_spec.SetField(question.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := qc.mutation.UpdatedAt(); ok {
		_spec.SetField(question.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := qc.mutation.Criteria(); ok {
		_spec.SetField(question.FieldCriteria, field.TypeString, value)
		_node.Criteria = value
	}
	if value, ok := qc.mutation.Hint(); ok {
		_spec.SetField(question.FieldHint, field.TypeString, value)
		_node.Hint = value
	}
	if value, ok := qc.mutation.Content(); ok {
		_spec.SetField(question.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if nodes := qc.mutation.ScenarioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   question.ScenarioTable,
			Columns: []string{question.ScenarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scenario.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ScenarioID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Question.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuestionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (qc *QuestionCreate) OnConflict(opts ...sql.ConflictOption) *QuestionUpsertOne {
	qc.conflict = opts
	return &QuestionUpsertOne{
		create: qc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Question.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (qc *QuestionCreate) OnConflictColumns(columns ...string) *QuestionUpsertOne {
	qc.conflict = append(qc.conflict, sql.ConflictColumns(columns...))
	return &QuestionUpsertOne{
		create: qc,
	}
}

type (
	// QuestionUpsertOne is the builder for "upsert"-ing
	//  one Question node.
	QuestionUpsertOne struct {
		create *QuestionCreate
	}

	// QuestionUpsert is the "OnConflict" setter.
	QuestionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *QuestionUpsert) SetUpdatedAt(v time.Time) *QuestionUpsert {
	u.Set(question.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuestionUpsert) UpdateUpdatedAt() *QuestionUpsert {
	u.SetExcluded(question.FieldUpdatedAt)
	return u
}

// SetScenarioID sets the "scenario_id" field.
func (u *QuestionUpsert) SetScenarioID(v uint64) *QuestionUpsert {
	u.Set(question.FieldScenarioID, v)
	return u
}

// UpdateScenarioID sets the "scenario_id" field to the value that was provided on create.
func (u *QuestionUpsert) UpdateScenarioID() *QuestionUpsert {
	u.SetExcluded(question.FieldScenarioID)
	return u
}

// SetCriteria sets the "criteria" field.
func (u *QuestionUpsert) SetCriteria(v string) *QuestionUpsert {
	u.Set(question.FieldCriteria, v)
	return u
}

// UpdateCriteria sets the "criteria" field to the value that was provided on create.
func (u *QuestionUpsert) UpdateCriteria() *QuestionUpsert {
	u.SetExcluded(question.FieldCriteria)
	return u
}

// SetHint sets the "hint" field.
func (u *QuestionUpsert) SetHint(v string) *QuestionUpsert {
	u.Set(question.FieldHint, v)
	return u
}

// UpdateHint sets the "hint" field to the value that was provided on create.
func (u *QuestionUpsert) UpdateHint() *QuestionUpsert {
	u.SetExcluded(question.FieldHint)
	return u
}

// SetContent sets the "content" field.
func (u *QuestionUpsert) SetContent(v string) *QuestionUpsert {
	u.Set(question.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *QuestionUpsert) UpdateContent() *QuestionUpsert {
	u.SetExcluded(question.FieldContent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Question.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(question.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuestionUpsertOne) UpdateNewValues() *QuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(question.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(question.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Question.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QuestionUpsertOne) Ignore() *QuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuestionUpsertOne) DoNothing() *QuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuestionCreate.OnConflict
// documentation for more info.
func (u *QuestionUpsertOne) Update(set func(*QuestionUpsert)) *QuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuestionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuestionUpsertOne) SetUpdatedAt(v time.Time) *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuestionUpsertOne) UpdateUpdatedAt() *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetScenarioID sets the "scenario_id" field.
func (u *QuestionUpsertOne) SetScenarioID(v uint64) *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.SetScenarioID(v)
	})
}

// UpdateScenarioID sets the "scenario_id" field to the value that was provided on create.
func (u *QuestionUpsertOne) UpdateScenarioID() *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateScenarioID()
	})
}

// SetCriteria sets the "criteria" field.
func (u *QuestionUpsertOne) SetCriteria(v string) *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.SetCriteria(v)
	})
}

// UpdateCriteria sets the "criteria" field to the value that was provided on create.
func (u *QuestionUpsertOne) UpdateCriteria() *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateCriteria()
	})
}

// SetHint sets the "hint" field.
func (u *QuestionUpsertOne) SetHint(v string) *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.SetHint(v)
	})
}

// UpdateHint sets the "hint" field to the value that was provided on create.
func (u *QuestionUpsertOne) UpdateHint() *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateHint()
	})
}

// SetContent sets the "content" field.
func (u *QuestionUpsertOne) SetContent(v string) *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *QuestionUpsertOne) UpdateContent() *QuestionUpsertOne {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateContent()
	})
}

// Exec executes the query.
func (u *QuestionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuestionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuestionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QuestionUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QuestionUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QuestionCreateBulk is the builder for creating many Question entities in bulk.
type QuestionCreateBulk struct {
	config
	err      error
	builders []*QuestionCreate
	conflict []sql.ConflictOption
}

// Save creates the Question entities in the database.
func (qcb *QuestionCreateBulk) Save(ctx context.Context) ([]*Question, error) {
	if qcb.err != nil {
		return nil, qcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(qcb.builders))
	nodes := make([]*Question, len(qcb.builders))
	mutators := make([]Mutator, len(qcb.builders))
	for i := range qcb.builders {
		func(i int, root context.Context) {
			builder := qcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = qcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qcb *QuestionCreateBulk) SaveX(ctx context.Context) []*Question {
	v, err := qcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qcb *QuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := qcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qcb *QuestionCreateBulk) ExecX(ctx context.Context) {
	if err := qcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Question.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuestionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (qcb *QuestionCreateBulk) OnConflict(opts ...sql.ConflictOption) *QuestionUpsertBulk {
	qcb.conflict = opts
	return &QuestionUpsertBulk{
		create: qcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Question.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (qcb *QuestionCreateBulk) OnConflictColumns(columns ...string) *QuestionUpsertBulk {
	qcb.conflict = append(qcb.conflict, sql.ConflictColumns(columns...))
	return &QuestionUpsertBulk{
		create: qcb,
	}
}

// QuestionUpsertBulk is the builder for "upsert"-ing
// a bulk of Question nodes.
type QuestionUpsertBulk struct {
	create *QuestionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Question.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(question.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuestionUpsertBulk) UpdateNewValues() *QuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(question.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(question.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Question.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QuestionUpsertBulk) Ignore() *QuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuestionUpsertBulk) DoNothing() *QuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuestionCreateBulk.OnConflict
// documentation for more info.
func (u *QuestionUpsertBulk) Update(set func(*QuestionUpsert)) *QuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuestionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuestionUpsertBulk) SetUpdatedAt(v time.Time) *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuestionUpsertBulk) UpdateUpdatedAt() *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetScenarioID sets the "scenario_id" field.
func (u *QuestionUpsertBulk) SetScenarioID(v uint64) *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.SetScenarioID(v)
	})
}

// UpdateScenarioID sets the "scenario_id" field to the value that was provided on create.
func (u *QuestionUpsertBulk) UpdateScenarioID() *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateScenarioID()
	})
}

// SetCriteria sets the "criteria" field.
func (u *QuestionUpsertBulk) SetCriteria(v string) *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.SetCriteria(v)
	})
}

// UpdateCriteria sets the "criteria" field to the value that was provided on create.
func (u *QuestionUpsertBulk) UpdateCriteria() *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateCriteria()
	})
}

// SetHint sets the "hint" field.
func (u *QuestionUpsertBulk) SetHint(v string) *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.SetHint(v)
	})
}

// UpdateHint sets the "hint" field to the value that was provided on create.
func (u *QuestionUpsertBulk) UpdateHint() *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateHint()
	})
}

// SetContent sets the "content" field.
func (u *QuestionUpsertBulk) SetContent(v string) *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *QuestionUpsertBulk) UpdateContent() *QuestionUpsertBulk {
	return u.Update(func(s *QuestionUpsert) {
		s.UpdateContent()
	})
}

// Exec executes the query.
func (u *QuestionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QuestionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuestionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuestionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
