// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"ekko/pkg/ent/answersubmission"
	"ekko/pkg/ent/predicate"
	"ekko/pkg/ent/scenariocandidate"
	"ekko/pkg/ent/submissionattempt"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubmissionAttemptQuery is the builder for querying SubmissionAttempt entities.
type SubmissionAttemptQuery struct {
	config
	ctx                   *QueryContext
	order                 []submissionattempt.OrderOption
	inters                []Interceptor
	predicates            []predicate.SubmissionAttempt
	withScenarioCandidate *ScenarioCandidateQuery
	withAnswers           *AnswerSubmissionQuery
	modifiers             []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubmissionAttemptQuery builder.
func (saq *SubmissionAttemptQuery) Where(ps ...predicate.SubmissionAttempt) *SubmissionAttemptQuery {
	saq.predicates = append(saq.predicates, ps...)
	return saq
}

// Limit the number of records to be returned by this query.
func (saq *SubmissionAttemptQuery) Limit(limit int) *SubmissionAttemptQuery {
	saq.ctx.Limit = &limit
	return saq
}

// Offset to start from.
func (saq *SubmissionAttemptQuery) Offset(offset int) *SubmissionAttemptQuery {
	saq.ctx.Offset = &offset
	return saq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (saq *SubmissionAttemptQuery) Unique(unique bool) *SubmissionAttemptQuery {
	saq.ctx.Unique = &unique
	return saq
}

// Order specifies how the records should be ordered.
func (saq *SubmissionAttemptQuery) Order(o ...submissionattempt.OrderOption) *SubmissionAttemptQuery {
	saq.order = append(saq.order, o...)
	return saq
}

// QueryScenarioCandidate chains the current query on the "scenario_candidate" edge.
func (saq *SubmissionAttemptQuery) QueryScenarioCandidate() *ScenarioCandidateQuery {
	query := (&ScenarioCandidateClient{config: saq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := saq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := saq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(submissionattempt.Table, submissionattempt.FieldID, selector),
			sqlgraph.To(scenariocandidate.Table, scenariocandidate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, submissionattempt.ScenarioCandidateTable, submissionattempt.ScenarioCandidateColumn),
		)
		fromU = sqlgraph.SetNeighbors(saq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAnswers chains the current query on the "answers" edge.
func (saq *SubmissionAttemptQuery) QueryAnswers() *AnswerSubmissionQuery {
	query := (&AnswerSubmissionClient{config: saq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := saq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := saq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(submissionattempt.Table, submissionattempt.FieldID, selector),
			sqlgraph.To(answersubmission.Table, answersubmission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, submissionattempt.AnswersTable, submissionattempt.AnswersColumn),
		)
		fromU = sqlgraph.SetNeighbors(saq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubmissionAttempt entity from the query.
// Returns a *NotFoundError when no SubmissionAttempt was found.
func (saq *SubmissionAttemptQuery) First(ctx context.Context) (*SubmissionAttempt, error) {
	nodes, err := saq.Limit(1).All(setContextOp(ctx, saq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{submissionattempt.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (saq *SubmissionAttemptQuery) FirstX(ctx context.Context) *SubmissionAttempt {
	node, err := saq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubmissionAttempt ID from the query.
// Returns a *NotFoundError when no SubmissionAttempt ID was found.
func (saq *SubmissionAttemptQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = saq.Limit(1).IDs(setContextOp(ctx, saq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{submissionattempt.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (saq *SubmissionAttemptQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := saq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubmissionAttempt entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubmissionAttempt entity is found.
// Returns a *NotFoundError when no SubmissionAttempt entities are found.
func (saq *SubmissionAttemptQuery) Only(ctx context.Context) (*SubmissionAttempt, error) {
	nodes, err := saq.Limit(2).All(setContextOp(ctx, saq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{submissionattempt.Label}
	default:
		return nil, &NotSingularError{submissionattempt.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (saq *SubmissionAttemptQuery) OnlyX(ctx context.Context) *SubmissionAttempt {
	node, err := saq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubmissionAttempt ID in the query.
// Returns a *NotSingularError when more than one SubmissionAttempt ID is found.
// Returns a *NotFoundError when no entities are found.
func (saq *SubmissionAttemptQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = saq.Limit(2).IDs(setContextOp(ctx, saq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{submissionattempt.Label}
	default:
		err = &NotSingularError{submissionattempt.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (saq *SubmissionAttemptQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := saq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubmissionAttempts.
func (saq *SubmissionAttemptQuery) All(ctx context.Context) ([]*SubmissionAttempt, error) {
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryAll)
	if err := saq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubmissionAttempt, *SubmissionAttemptQuery]()
	return withInterceptors[[]*SubmissionAttempt](ctx, saq, qr, saq.inters)
}

// AllX is like All, but panics if an error occurs.
func (saq *SubmissionAttemptQuery) AllX(ctx context.Context) []*SubmissionAttempt {
	nodes, err := saq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubmissionAttempt IDs.
func (saq *SubmissionAttemptQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if saq.ctx.Unique == nil && saq.path != nil {
		saq.Unique(true)
	}
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryIDs)
	if err = saq.Select(submissionattempt.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (saq *SubmissionAttemptQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := saq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (saq *SubmissionAttemptQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryCount)
	if err := saq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, saq, querierCount[*SubmissionAttemptQuery](), saq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (saq *SubmissionAttemptQuery) CountX(ctx context.Context) int {
	count, err := saq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (saq *SubmissionAttemptQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryExist)
	switch _, err := saq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (saq *SubmissionAttemptQuery) ExistX(ctx context.Context) bool {
	exist, err := saq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubmissionAttemptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (saq *SubmissionAttemptQuery) Clone() *SubmissionAttemptQuery {
	if saq == nil {
		return nil
	}
	return &SubmissionAttemptQuery{
		config:                saq.config,
		ctx:                   saq.ctx.Clone(),
		order:                 append([]submissionattempt.OrderOption{}, saq.order...),
		inters:                append([]Interceptor{}, saq.inters...),
		predicates:            append([]predicate.SubmissionAttempt{}, saq.predicates...),
		withScenarioCandidate: saq.withScenarioCandidate.Clone(),
		withAnswers:           saq.withAnswers.Clone(),
		// clone intermediate query.
		sql:       saq.sql.Clone(),
		path:      saq.path,
		modifiers: append([]func(*sql.Selector){}, saq.modifiers...),
	}
}

// WithScenarioCandidate tells the query-builder to eager-load the nodes that are connected to
// the "scenario_candidate" edge. The optional arguments are used to configure the query builder of the edge.
func (saq *SubmissionAttemptQuery) WithScenarioCandidate(opts ...func(*ScenarioCandidateQuery)) *SubmissionAttemptQuery {
	query := (&ScenarioCandidateClient{config: saq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	saq.withScenarioCandidate = query
	return saq
}

// WithAnswers tells the query-builder to eager-load the nodes that are connected to
// the "answers" edge. The optional arguments are used to configure the query builder of the edge.
func (saq *SubmissionAttemptQuery) WithAnswers(opts ...func(*AnswerSubmissionQuery)) *SubmissionAttemptQuery {
	query := (&AnswerSubmissionClient{config: saq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	saq.withAnswers = query
	return saq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubmissionAttempt.Query().
//		GroupBy(submissionattempt.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (saq *SubmissionAttemptQuery) GroupBy(field string, fields ...string) *SubmissionAttemptGroupBy {
	saq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubmissionAttemptGroupBy{build: saq}
	grbuild.flds = &saq.ctx.Fields
	grbuild.label = submissionattempt.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SubmissionAttempt.Query().
//		Select(submissionattempt.FieldCreatedAt).
//		Scan(ctx, &v)
func (saq *SubmissionAttemptQuery) Select(fields ...string) *SubmissionAttemptSelect {
	saq.ctx.Fields = append(saq.ctx.Fields, fields...)
	sbuild := &SubmissionAttemptSelect{SubmissionAttemptQuery: saq}
	sbuild.label = submissionattempt.Label
	sbuild.flds, sbuild.scan = &saq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubmissionAttemptSelect configured with the given aggregations.
func (saq *SubmissionAttemptQuery) Aggregate(fns ...AggregateFunc) *SubmissionAttemptSelect {
	return saq.Select().Aggregate(fns...)
}

func (saq *SubmissionAttemptQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range saq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, saq); err != nil {
				return err
			}
		}
	}
	for _, f := range saq.ctx.Fields {
		if !submissionattempt.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if saq.path != nil {
		prev, err := saq.path(ctx)
		if err != nil {
			return err
		}
		saq.sql = prev
	}
	return nil
}

func (saq *SubmissionAttemptQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubmissionAttempt, error) {
	var (
		nodes       = []*SubmissionAttempt{}
		_spec       = saq.querySpec()
		loadedTypes = [2]bool{
			saq.withScenarioCandidate != nil,
			saq.withAnswers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubmissionAttempt).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubmissionAttempt{config: saq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(saq.modifiers) > 0 {
		_spec.Modifiers = saq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, saq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := saq.withScenarioCandidate; query != nil {
		if err := saq.loadScenarioCandidate(ctx, query, nodes, nil,
			func(n *SubmissionAttempt, e *ScenarioCandidate) { n.Edges.ScenarioCandidate = e }); err != nil {
			return nil, err
		}
	}
	if query := saq.withAnswers; query != nil {
		if err := saq.loadAnswers(ctx, query, nodes,
			func(n *SubmissionAttempt) { n.Edges.Answers = []*AnswerSubmission{} },
			func(n *SubmissionAttempt, e *AnswerSubmission) { n.Edges.Answers = append(n.Edges.Answers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (saq *SubmissionAttemptQuery) loadScenarioCandidate(ctx context.Context, query *ScenarioCandidateQuery, nodes []*SubmissionAttempt, init func(*SubmissionAttempt), assign func(*SubmissionAttempt, *ScenarioCandidate)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*SubmissionAttempt)
	for i := range nodes {
		fk := nodes[i].ScenarioCandidateID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(scenariocandidate.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "scenario_candidate_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (saq *SubmissionAttemptQuery) loadAnswers(ctx context.Context, query *AnswerSubmissionQuery, nodes []*SubmissionAttempt, init func(*SubmissionAttempt), assign func(*SubmissionAttempt, *AnswerSubmission)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*SubmissionAttempt)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(answersubmission.FieldSubmissionAttemptID)
	}
	query.Where(predicate.AnswerSubmission(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(submissionattempt.AnswersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SubmissionAttemptID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "submission_attempt_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (saq *SubmissionAttemptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := saq.querySpec()
	if len(saq.modifiers) > 0 {
		_spec.Modifiers = saq.modifiers
	}
	_spec.Node.Columns = saq.ctx.Fields
	if len(saq.ctx.Fields) > 0 {
		_spec.Unique = saq.ctx.Unique != nil && *saq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, saq.driver, _spec)
}

func (saq *SubmissionAttemptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(submissionattempt.Table, submissionattempt.Columns, sqlgraph.NewFieldSpec(submissionattempt.FieldID, field.TypeUint64))
	_spec.From = saq.sql
	if unique := saq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if saq.path != nil {
		_spec.Unique = true
	}
	if fields := saq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, submissionattempt.FieldID)
		for i := range fields {
			if fields[i] != submissionattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if saq.withScenarioCandidate != nil {
			_spec.Node.AddColumnOnce(submissionattempt.FieldScenarioCandidateID)
		}
	}
	if ps := saq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := saq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := saq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := saq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (saq *SubmissionAttemptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(saq.driver.Dialect())
	t1 := builder.Table(submissionattempt.Table)
	columns := saq.ctx.Fields
	if len(columns) == 0 {
		columns = submissionattempt.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if saq.sql != nil {
		selector = saq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if saq.ctx.Unique != nil && *saq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range saq.modifiers {
		m(selector)
	}
	for _, p := range saq.predicates {
		p(selector)
	}
	for _, p := range saq.order {
		p(selector)
	}
	if offset := saq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := saq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (saq *SubmissionAttemptQuery) ForUpdate(opts ...sql.LockOption) *SubmissionAttemptQuery {
	if saq.driver.Dialect() == dialect.Postgres {
		saq.Unique(false)
	}
	saq.modifiers = append(saq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return saq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (saq *SubmissionAttemptQuery) ForShare(opts ...sql.LockOption) *SubmissionAttemptQuery {
	if saq.driver.Dialect() == dialect.Postgres {
		saq.Unique(false)
	}
	saq.modifiers = append(saq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return saq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (saq *SubmissionAttemptQuery) Modify(modifiers ...func(s *sql.Selector)) *SubmissionAttemptSelect {
	saq.modifiers = append(saq.modifiers, modifiers...)
	return saq.Select()
}

// SubmissionAttemptGroupBy is the group-by builder for SubmissionAttempt entities.
type SubmissionAttemptGroupBy struct {
	selector
	build *SubmissionAttemptQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sagb *SubmissionAttemptGroupBy) Aggregate(fns ...AggregateFunc) *SubmissionAttemptGroupBy {
	sagb.fns = append(sagb.fns, fns...)
	return sagb
}

// Scan applies the selector query and scans the result into the given value.
func (sagb *SubmissionAttemptGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sagb.build.ctx, ent.OpQueryGroupBy)
	if err := sagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubmissionAttemptQuery, *SubmissionAttemptGroupBy](ctx, sagb.build, sagb, sagb.build.inters, v)
}

func (sagb *SubmissionAttemptGroupBy) sqlScan(ctx context.Context, root *SubmissionAttemptQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sagb.fns))
	for _, fn := range sagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sagb.flds)+len(sagb.fns))
		for _, f := range *sagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubmissionAttemptSelect is the builder for selecting fields of SubmissionAttempt entities.
type SubmissionAttemptSelect struct {
	*SubmissionAttemptQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sas *SubmissionAttemptSelect) Aggregate(fns ...AggregateFunc) *SubmissionAttemptSelect {
	sas.fns = append(sas.fns, fns...)
	return sas
}

// Scan applies the selector query and scans the result into the given value.
func (sas *SubmissionAttemptSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sas.ctx, ent.OpQuerySelect)
	if err := sas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubmissionAttemptQuery, *SubmissionAttemptSelect](ctx, sas.SubmissionAttemptQuery, sas, sas.inters, v)
}

func (sas *SubmissionAttemptSelect) sqlScan(ctx context.Context, root *SubmissionAttemptQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sas.fns))
	for _, fn := range sas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sas *SubmissionAttemptSelect) Modify(modifiers ...func(s *sql.Selector)) *SubmissionAttemptSelect {
	sas.modifiers = append(sas.modifiers, modifiers...)
	return sas
}
