// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ekko/package/ent/predicate"
	"ekko/package/ent/scenariocandidate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScenarioCandidateDelete is the builder for deleting a ScenarioCandidate entity.
type ScenarioCandidateDelete struct {
	config
	hooks    []Hook
	mutation *ScenarioCandidateMutation
}

// Where appends a list predicates to the ScenarioCandidateDelete builder.
func (scd *ScenarioCandidateDelete) Where(ps ...predicate.ScenarioCandidate) *ScenarioCandidateDelete {
	scd.mutation.Where(ps...)
	return scd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scd *ScenarioCandidateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scd.sqlExec, scd.mutation, scd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scd *ScenarioCandidateDelete) ExecX(ctx context.Context) int {
	n, err := scd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scd *ScenarioCandidateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(scenariocandidate.Table, sqlgraph.NewFieldSpec(scenariocandidate.FieldID, field.TypeUint64))
	if ps := scd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scd.mutation.done = true
	return affected, err
}

// ScenarioCandidateDeleteOne is the builder for deleting a single ScenarioCandidate entity.
type ScenarioCandidateDeleteOne struct {
	scd *ScenarioCandidateDelete
}

// Where appends a list predicates to the ScenarioCandidateDelete builder.
func (scdo *ScenarioCandidateDeleteOne) Where(ps ...predicate.ScenarioCandidate) *ScenarioCandidateDeleteOne {
	scdo.scd.mutation.Where(ps...)
	return scdo
}

// Exec executes the deletion query.
func (scdo *ScenarioCandidateDeleteOne) Exec(ctx context.Context) error {
	n, err := scdo.scd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{scenariocandidate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scdo *ScenarioCandidateDeleteOne) ExecX(ctx context.Context) {
	if err := scdo.Exec(ctx); err != nil {
		panic(err)
	}
}
