// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.1
// source: api/ekko.proto

package ekko

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmissionStatus int32

const (
	SubmissionStatus_SUBMISSION_STATUS_UNKNOWN     SubmissionStatus = 0
	SubmissionStatus_SUBMISSION_STATUS_IN_PROGRESS SubmissionStatus = 1
	SubmissionStatus_SUBMISSION_STATUS_FAILED      SubmissionStatus = 2
	SubmissionStatus_SUBMISSION_STATUS_SUCCESS     SubmissionStatus = 3
)

// Enum value maps for SubmissionStatus.
var (
	SubmissionStatus_name = map[int32]string{
		0: "SUBMISSION_STATUS_UNKNOWN",
		1: "SUBMISSION_STATUS_IN_PROGRESS",
		2: "SUBMISSION_STATUS_FAILED",
		3: "SUBMISSION_STATUS_SUCCESS",
	}
	SubmissionStatus_value = map[string]int32{
		"SUBMISSION_STATUS_UNKNOWN":     0,
		"SUBMISSION_STATUS_IN_PROGRESS": 1,
		"SUBMISSION_STATUS_FAILED":      2,
		"SUBMISSION_STATUS_SUCCESS":     3,
	}
)

func (x SubmissionStatus) Enum() *SubmissionStatus {
	p := new(SubmissionStatus)
	*p = x
	return p
}

func (x SubmissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ekko_proto_enumTypes[0].Descriptor()
}

func (SubmissionStatus) Type() protoreflect.EnumType {
	return &file_api_ekko_proto_enumTypes[0]
}

func (x SubmissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SubmissionStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SubmissionStatus(num)
	return nil
}

// Deprecated: Use SubmissionStatus.Descriptor instead.
func (SubmissionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_ekko_proto_rawDescGZIP(), []int{0}
}

var File_api_ekko_proto protoreflect.FileDescriptor

var file_api_ekko_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6b, 0x6b, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x65, 0x6b, 0x6b, 0x6f, 0x2a, 0x91, 0x01, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x19, 0x53,
	0x55, 0x42, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x53, 0x55,
	0x42, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x1c, 0x0a,
	0x18, 0x53, 0x55, 0x42, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x53,
	0x55, 0x42, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x03, 0x32, 0x06, 0x0a, 0x04, 0x45, 0x6b,
	0x6b, 0x6f, 0x42, 0x0f, 0x5a, 0x0d, 0x65, 0x6b, 0x6b, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x65,
	0x6b, 0x6b, 0x6f,
}

var (
	file_api_ekko_proto_rawDescOnce sync.Once
	file_api_ekko_proto_rawDescData = file_api_ekko_proto_rawDesc
)

func file_api_ekko_proto_rawDescGZIP() []byte {
	file_api_ekko_proto_rawDescOnce.Do(func() {
		file_api_ekko_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ekko_proto_rawDescData)
	})
	return file_api_ekko_proto_rawDescData
}

var file_api_ekko_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_ekko_proto_goTypes = []interface{}{
	(SubmissionStatus)(0), // 0: ekko.SubmissionStatus
}
var file_api_ekko_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ekko_proto_init() }
func file_api_ekko_proto_init() {
	if File_api_ekko_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ekko_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ekko_proto_goTypes,
		DependencyIndexes: file_api_ekko_proto_depIdxs,
		EnumInfos:         file_api_ekko_proto_enumTypes,
	}.Build()
	File_api_ekko_proto = out.File
	file_api_ekko_proto_rawDesc = nil
	file_api_ekko_proto_goTypes = nil
	file_api_ekko_proto_depIdxs = nil
}
